### ISSUE TITLE
Add DST timezone possible issues

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#254]
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation

DynamicDaylightTimeDisabled = 1 
DaylightStart != 0
StandardStart != 0
Timezonekeyname = null/empty  

If DynamicDaylightTimeDisabled =1 and Start dates set to Zero I would warn = Daylight savings auto adjustment is disabled
If DynamicDaylightTimeDisabled =1 and Start dates set to non zero values = alert that the settings could cause issues.

Timezonekeyname is null or empty, provide to take action to address this by switching the timezone on the computer.

**Comment by lusassl-msft** [comment]
Not sure if this is because of a broken configuration on my lab machine but I get the following error (I haven't had time to check it out yet.):

VERBOSE: Attempting to open the Base Key 'LocalMachine' on Server '2012R2-EX2016'
VERBOSE: Attempting to open the Sub Key 'SYSTEM\CurrentControlSet\Control\TimeZoneInformation'
VERBOSE: Attempting to get the value 'DaylightStart'
Build-OperatingSystemObject : Exception setting "TimeZoneInformation": "Cannot convert value
"@{DynamicDaylightTimeDisabled=0; TimeZoneKeyName=E. South America Standard Time; StandardStart=System.Object[];
DaylightStart=System.Object[]; DstIssueDetected=; ActionsToTake=System.Object[]}" to type
"HealthChecker.TimeZoneInformationObject". Error: "Cannot convert the "@{DynamicDaylightTimeDisabled=0;
TimeZoneKeyName=E. South America Standard Time; StandardStart=System.Object[]; DaylightStart=System.Object[];
DstIssueDetected=; ActionsToTake=System.Object[]}" value of type "System.Management.Automation.PSCustomObject" to type
"HealthChecker.TimeZoneInformationObject".""
At C:\Users\Administrator.CONTOSO\Desktop\Dev6\HealthChecker.ps1:3467 char:33
+     $HealthExSvrObj.OSVersion = Build-OperatingSystemObject -Machine_Name $Machi ...
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Build-OperatingSystemObject], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting,Build-OperatingSystemObject

**Comment by dpaulson45** [comment]
Will have to keep an eye out for that, but I didn't run into any issues with my labs that I ran the script on.

**Comment by lusassl-msft** [comment]
Btw: The issue I mentioned above has been solved with latest version 2.39.1
