### ISSUE TITLE
Add SMB3 vulnerability fix to Dev3.0.0 

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#297]
Add commit e98a4d08ff53838e612b969cde2c416467998888 to Dev3.0.0

**Comment by dpaulson45** [comment]
@lusassl-msft can you confirm why we are only looking at builds 18362 and 18363 vs looking at 18363 and older? (17763 etc...)

Does the issue not occur on the older ones? I didn't find any reference to confirm this, wasn't sure how the support model fully works for Windows Server and if that played a roll or not.

**Comment by lusassl-msft** [comment]
@dpaulson45 affected builds are 1903 (build number 18362) and 1909 (build number 18363).
CVE: https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2020-0796
Build number table: https://en.wikipedia.org/wiki/Windows_10_version_history

AFAIK these builds are affected because of the newly introduced compression capability with SMB 3.1.1 which is not available with older builds (like 17763).

**Comment by dpaulson45** [comment]
commit added in bc5ec7e4b1dd3a3f8199b8b2709b130b51f7a1a3
