### ISSUE TITLE
Determine if we always want to show Server Pending Reboot even if it isn't pending a reboot

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#334]
Determine if we want to display the field of the Server Pending Reboot set to false or not.

**Comment by worldsdream** [comment]
If it does not need a server pending reboot. There should not be written that it needs to reboot. 

Why was this added in the first place? I would love to know.

**Comment by dpaulson45** [comment]
When an application or windows is automatically updated and needs to be rebooted to finish its update. When in this state, depending on what received an update can cause a performance impact. You should always reboot the server when it is asking you to.

**Comment by JCothern** [comment]
I actually feel this should be in the initial table near the Hyperthreading
or something.  We recently ran across the environment weeks after a patch
cycle and found 20 server of 120 exchange servers saying they where pending
a reboot from a file change.  But it was hard to find those as we had to
then go thru 120 Txt files instead of the summary report.

**Comment by worldsdream** [comment]
@dpaulson45 
Yes, if it needs a reboot, then we need to see it in the logs/report. That’s the best. 

I just didn’t understand the title, it’s a bit confusing: “Determine if we always want to show Server Pending Reboot even if it isn't pending a reboot”. 


@JCothern Yes, the best would to stuff all the information in the report. Because we love to generate the report for one specific ex server or all of them.

**Comment by dpaulson45** [comment]
@JCothern the new layout in Dev3.0 will have a much better layout of the output.

@worldsdream, it boils down to if we always want the column displayed if in fact server is pending reboot or not (Server Pending Reboot: True/False) There is also a concern when it comes to possible false positives.
