### ISSUE TITLE
Feature to add in script - Check for NIC Power management setting

### ISSUE THREAD

**Issue by worldsdream** [dpaulson45/HealthChecker#340]
Hi there,

Can this be added to the script?

https://www.alitajran.com/disable-nic-power-management-in-exchange-best-practice/

Thanks. 
If it’s already added, can you tell me where? I can’t seem to find it.

**Comment by lusassl-msft** [comment]
Need to check if this is already covered when OS power plan is set to "High Performance"

**Comment by worldsdream** [comment]
@lusassl-msft I think it’s added to the latest version, am I right?

On a Hyper-v host, it’s telling me that it’s enabled. When I go to the nic power management settings, I dont have the option to disable it. 

Microsoft is telling in the sleepy nic article that if you don’t see the option in the nic management, it means that it’s already set. 

Whats going wrong? Let me know if you need more information or screenshots. 

I have exchange servers running om hyper-v and on vmware. I have not yet tried it on the vmware host. Will try and let you know.

**Comment by lusassl-msft** [comment]
@worldsdream yes, it was added with v2.44.0 and optimized with v.2.44.1. Unfortunately it's not easy to detect if a NIC support power saving. At the moment we're doing some kind of best guess. We run through all active NICs on the system and check if the PnPCapabilities is set to 24 (hex 0x18) which is the same as unchecking all three checkboxes. If it's not set to 24 or if it doesn't exist, we display a yellow warning next to the support.microsoft.com article where we describe the problem. I've tested to set the PnPCapabilities value to 24 via registry on a system with NIC that doesn't support power management. It does not have had any impact on the system so I decided to implement the first version of the check as kind of best guess. I stumbled across a vmware vm which had the power management capabilities checkboxes displayed on the NIC settings but no PnPCapabilities registry key exists. It was also not possible to properly determine the capabilities if the script was executed on 
 a VM where the NIC doesn't have the checkboxes displayed but on the hypervisor they was. 
So, it seems that there are many different scenarios and due to my limited resources I was not able to validate each of them. 
I'm thinking about to modify the check and display a warning only if the PnPCapabilities value is available and if it's not available to just show a note to validate the capabilities manually and configure the NIC either on the NIC itself or via registry key. I have to discuss this with @dpaulson45 and come back to you with more details.
