### ISSUE TITLE
Add data collection for SchUseStrongCrypto of the registry

### ISSUE THREAD

**Issue by dpaulson45** [dpaulson45/HealthChecker#482]
Running into some odd issues where some applications use .NET TLS version by running this command: 

```
[System.Net.ServicePointManager]::SecurityProtocol
```

In order to call this out a little better, throw a warning if the above contains `TLS` or `TLS11` when we have them disabled.

https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#schusestrongcrypto
https://techcommunity.microsoft.com/t5/exchange-team-blog/exchange-server-tls-guidance-part-3-turning-off-tls-1-0-1-1/ba-p/607898

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v2.0.50727]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v2.0.50727]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]
"SystemDefaultTlsVersions"=dword:00000001
"SchUseStrongCrypto"=dword:00000001
```

**Comment by dpaulson45** [comment]
Currently, additional information is being collected but `[System.Net.ServicePointManager]::SecurityProtocol` is still returning `TLS`, `TLS11` when we have disabled them in the registry correctly when on Exchange 2019/Windows 2019. This needs to be looked into before we provide a warning.

**Comment by Karl-WE** [comment]
Hello @dpaulson45 if this helps you I can provide a regkey or xml for these checks. Currently helping customers to get their TLS on 1.2 and save ciphers according to SSLLabs checks. 

Your script is already doing great to check the config
[System.Net.ServicePointManager]::SecurityProtocol should be set to TLS 1.2 too, otherwise connections to public repo like github or downloads via Nuget are blocked

refer:
https://devblogs.microsoft.com/powershell/powershell-gallery-tls-support/
