### ISSUE TITLE
[Issue] .NET Framework: 4.5.2 - Warning Recommended .NET Version is 4.5.2 

### ISSUE THREAD

**Issue by johnwblue** [dpaulson45/HealthChecker#527]
**Describe the issue**
The script issues a "warning" for a matched .net version level

**Expected behavior**
Change the word "warning" to something else.

**Comment by dpaulson45** [comment]
@johnwblue can you please provide the following from the output:

- Exchange Build Number
- OS Version 
- NET

**Comment by johnwblue** [comment]
Build Number: 15.0.847.32
Version: Microsoft Windows Server 2012 R2 Standard
.NET Framework: 4.5.2

**Comment by johnwblue** [comment]
Also sent files via email as requested.

Thanks!

**Comment by lusassl-msft** [comment]
We see this warning because we check for .Net 4.5.2 with hotfix (MaxSupportedVersion) in this case and this was not in place.

Anyway, we don't plan to update the script to show a more granular warning for the .NET 4.5.2 + Fix and .NET 4.6.1 + Fix. We don't have supported Exchange server versions that work with these versions anymore. So the best would be to upgrade to a supported .NET + CU combination.
