### ISSUE TITLE
.NET supportability

### ISSUE THREAD

**Issue by FredVH** [dpaulson45/HealthChecker#564]
One of your checks checks if the patch for CVE-2020-1147 is installed. If it's not, you refer to https://portal.msrc.microsoft.com/en-us/security-guidance/advisory/CVE-2020-1147. To get it fixed, I should install a CU for .NET: https://support.microsoft.com/help/4578969.
But the Exchange Supportability Matrix (https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019#microsoft-net-framework) clearly states: Versions of the .NET Framework that aren't listed in the tables below are not supported on any version of Exchange. _This includes minor and patch-level releases of the .NET Framework._
So installing the patch you refer to, could break my Exchange...

Kind regards
F.

**Comment by dpaulson45** [comment]
@FredVH what that article is referring to is something like .NET 4.6 where we don't support it. But, .NET 4.6.1 where 1 is the patch level, we do support. 

By installing that update that we are referring to does not break Exchange. 

If the Exchange team did not support a critical security flaw in .NET, that would be a major concern wouldn't you think? You just need to make sure you are installing the correct patch for the .NET version that you are on.

**Comment by dpaulson45** [comment]
Yes, it is a bit of bad wording. I will bring this up with some content people internally. 

This article might help explain it a little bit better. Even though it is for .NET Core. Same logic still applies.

https://docs.microsoft.com/en-us/dotnet/core/versions/

Major/Minor/Patch

Example: .NET 4.6.1

4 = Major
6 = Minor
1 = Patch

Where as the security patch that we are talking about should only be changing the Release/Revision number.

Previously in the script checked to make sure we require .NET 4.5.2 to be on X build of .NET which is basically requiring a KB due to performance releases. This never changed the .NET version that you saw of 4.5.2, but only what was in the registry. But this is now removed as being of .NET 4.5.2 means you are not on a supported build of Exchange.

This security patch is a similar concept. However, it isn't required to be installed by Exchange. We are just calling it out here to help you harden your Exchange Environment. 

https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed
